### ISSUE TITLE
not working while loading image from Url 

### ISSUE THREAD

**Issue by rajendrabohra** [davidschreiber/FancyCoverFlow#17]
Hi, 
Thanks for the source code, I am using it in my project to load image from url but facing problem it only show the center image not the right and left image. please help.

**Comment by davidschreiber** [comment]
Hi there, sorry for the late answer. Hope you could solve your problem in the meantime. It sounds like your forgot setting the size constraints on the coverflow item like this: `item.setLayoutParams(new FancyCoverFlow.LayoutParams(300, 600));`. Please calculate your width and/or height instead of using pixel values.

I will close this issue for now.

Regards, 
David
