### ISSUE TITLE
Gallery View is deprecated and should not be used anymore

### ISSUE THREAD

**Issue by davidschreiber** [davidschreiber/FancyCoverFlow#2]

**Comment by eveliotc** [comment]
:+1:

**Comment by AndroidDeveloperLB** [comment]
You could edit the code and make it extend from this gallery alternative:
https://github.com/falnatsheh/EcoGallery

This way it will also recycle views and avoid OOM .

EDIT: I've tried to merge them both, and it seems to work well, yet for some reason if I play with it for a long time, I get NPE and can't get to see where it occurs on. weird.

**Comment by davidschreiber** [comment]
Hello, thanks for your feedback. I also tried using `EcoGallery` and stumbled into several problems with the `EcoGallery` behaving different than the original `Gallery` widget. Currently I have not enough time digging into the implementation but if you are working on it, and are eager replacing the current engine feel free to do it and please send a pull request :-) (that would be great!)

Thanks,
David

**Comment by AndroidDeveloperLB** [comment]
Ok.
since I work at a company that works with another library (that not only has memory leaks but also costs money), I don't work on yours yet.
I've only tried to do some quick testing, so that they will consider using something else.

I also don't understand why I got NPE , since it didn't make any sense and didn't show any indication of where exactly it occurs, so that I could handle it...

However, maybe as a workaround, you can have the getView to set old items' imageViews' image to null, so that at least you'd delay the OOM. you could do it by using getFirstVisiblePosition() and getLastVisiblePosition().
