### ISSUE TITLE
not Scrolling over the buttons 

### ISSUE THREAD

**Issue by Nezam** [davidschreiber/FancyCoverFlow#20]
On the example of Reflection `ViewGroupReflectionExample.java`,if you try to scroll over the cover by touching over the buttons it does'nt work as expected.

**Comment by davidschreiber** [comment]
Hi Nezam!

You are right, the button consumes all input events which prevents the cover flow from scrolling. In order to enable scrolling, the Cover Flow would need to implement improved touch event interception (e.g. check if child views can scroll). Since I don't have time to work on FancyCoverFlow at the moment, you could do this if you like and send me a pull request (would be great!).

Thanks,
David

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.
